services:
  contao_bootstrap.grid.grid_builder:
    class: ContaoBootstrap\Grid\GridBuilder

  contao_bootstrap.grid.grid_provider:
    class: ContaoBootstrap\Grid\GridProvider
    arguments:
      - '@contao_bootstrap.grid.grid_builder'

  ContaoBootstrap\Grid\Component\ContentElement\GridElementFactory:
    arguments:
      - "@templating"
      - "@translator"
      - "@netzmacht.contao_toolkit.routing.scope_matcher"
      - "@contao_bootstrap.grid.grid_provider"
      - "@contao_bootstrap.core.helper.color_rotate"
    tags:
      - { name: 'netzmacht.contao_toolkit.component.content_element_factory' }
      - { name: 'netzmacht.contao_toolkit.component.content_element', category: 'bs_grid', alias: 'bs_gridStart' }
      - { name: 'netzmacht.contao_toolkit.component.content_element', category: 'bs_grid', alias: 'bs_gridSeparator' }
      - { name: 'netzmacht.contao_toolkit.component.content_element', category: 'bs_grid', alias: 'bs_gridStop' }

  ContaoBootstrap\Grid\Component\Module\GridModuleFactory:
    arguments:
      - "@templating"
      - "@translator"
      - "@contao_bootstrap.grid.grid_provider"
    tags:
      - { name: 'netzmacht.contao_toolkit.component.frontend_module_factory' }
      - { name: 'netzmacht.contao_toolkit.component.frontend_module', category: 'miscellaneous', alias: 'bs_grid' }
